/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PageHome {
    }
    interface StickTank {
        "isColliding": (blocked: boolean) => Promise<void>;
        "isHit": () => Promise<void>;
        "size": number;
        "x": number;
        "y": number;
    }
    interface TankCj {
        "isColliding": (blocked: boolean) => Promise<void>;
        "isHit": () => Promise<void>;
        "size": number;
        "x": number;
        "y": number;
    }
}
declare global {
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLStickTankElement extends Components.StickTank, HTMLStencilElement {
    }
    var HTMLStickTankElement: {
        prototype: HTMLStickTankElement;
        new (): HTMLStickTankElement;
    };
    interface HTMLTankCjElement extends Components.TankCj, HTMLStencilElement {
    }
    var HTMLTankCjElement: {
        prototype: HTMLTankCjElement;
        new (): HTMLTankCjElement;
    };
    interface HTMLElementTagNameMap {
        "page-home": HTMLPageHomeElement;
        "stick-tank": HTMLStickTankElement;
        "tank-cj": HTMLTankCjElement;
    }
}
declare namespace LocalJSX {
    interface PageHome {
    }
    interface StickTank {
        "size"?: number;
        "x"?: number;
        "y"?: number;
    }
    interface TankCj {
        "size"?: number;
        "x"?: number;
        "y"?: number;
    }
    interface IntrinsicElements {
        "page-home": PageHome;
        "stick-tank": StickTank;
        "tank-cj": TankCj;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "stick-tank": LocalJSX.StickTank & JSXBase.HTMLAttributes<HTMLStickTankElement>;
            "tank-cj": LocalJSX.TankCj & JSXBase.HTMLAttributes<HTMLTankCjElement>;
        }
    }
}
