/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PageHome {
    }
    interface Tank1 {
        "x": number;
        "y": number;
    }
}
declare global {
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLTank1Element extends Components.Tank1, HTMLStencilElement {
    }
    var HTMLTank1Element: {
        prototype: HTMLTank1Element;
        new (): HTMLTank1Element;
    };
    interface HTMLElementTagNameMap {
        "page-home": HTMLPageHomeElement;
        "tank-1": HTMLTank1Element;
    }
}
declare namespace LocalJSX {
    interface PageHome {
    }
    interface Tank1 {
        "x"?: number;
        "y"?: number;
    }
    interface IntrinsicElements {
        "page-home": PageHome;
        "tank-1": Tank1;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "tank-1": LocalJSX.Tank1 & JSXBase.HTMLAttributes<HTMLTank1Element>;
        }
    }
}
